# Basic ECO lookup to fix "Unknown" issues
# Sources from various free chess data

ECO_DICT = {
    "A00": "Uncommon Opening",
    "A01": "Nimzovich-Larsen Attack",
    "A02": "Bird's Opening",
    "A03": "Bird's Opening",
    "A04": "Reti Opening",
    "A05": "Reti Opening",
    "A06": "Reti Opening",
    "A07": "King's Indian Attack",
    "A08": "King's Indian Attack",
    "A09": "Reti Opening",
    
    "A10": "English Opening",
    "A11": "English Opening, Caro-Kann Defensive System",
    "A12": "English Opening, Caro-Kann Defensive System",
    "A13": "English Opening",
    "A14": "English Opening",
    "A15": "English Opening",
    "A16": "English Opening",
    "A17": "English Opening",
    "A18": "English Opening, Mikenas-Carls",
    "A19": "English Opening, Mikenas-Carls",
    
    "A20": "English Opening",
    "A21": "English Opening",
    "A22": "English Opening",
    "A23": "English Opening, Bremen System",
    "A24": "English Opening, Bremen System",
    "A25": "English Opening, Sicilian Reverse",
    "A26": "English Opening, Closed System",
    "A27": "English Opening, Three Knights System",
    "A28": "English Opening, Four Knights System",
    "A29": "English Opening, Four Knights System",
    
    "A30": "English Opening, Symmetrical",
    "A31": "English Opening, Symmetrical, Benoni Formation",
    "A32": "English Opening, Symmetrical",
    "A33": "English Opening, Symmetrical",
    "A34": "English Opening, Symmetrical",
    "A35": "English Opening, Symmetrical",
    "A36": "English Opening, Symmetrical",
    "A37": "English Opening, Symmetrical",
    "A38": "English Opening, Symmetrical",
    "A39": "English Opening, Symmetrical, Main line with d4",
    
    "A40": "Queen's Pawn Game",
    "A41": "Queen's Pawn Game (with ...d6)",
    "A42": "Modern Defense, Averbakh System",
    "A43": "Old Benoni",
    "A44": "Old Benoni",
    "A45": "Queen's Pawn Game",
    "A46": "Queen's Pawn Game",
    "A47": "Queen's Indian Defense",
    "A48": "King's Indian, East Indian Defense",
    "A49": "King's Indian, Fianchetto without c4",
    
    "A50": "Queen's Pawn Game",
    "A51": "Budapest Gambit",
    "A52": "Budapest Gambit",
    "A53": "Old Indian Defense",
    "A54": "Old Indian, Ukrainian Variation",
    "A55": "Old Indian, Main line",
    "A56": "Benoni Defense",
    "A57": "Benko Gambit",
    "A58": "Benko Gambit",
    "A59": "Benko Gambit",
    
    "A60": "Benoni Defense",
    "A61": "Benoni",
    "A62": "Benoni, Fianchetto Variation",
    "A63": "Benoni, Fianchetto Variation",
    "A64": "Benoni, Fianchetto Variation",
    "A65": "Benoni, 6.e4",
    "A66": "Benoni, Pawn Storm Variation",
    "A67": "Benoni, Taimanov Variation",
    "A68": "Benoni, Four Pawns Attack",
    "A69": "Benoni, Four Pawns Attack",
    
    "A70": "Benoni, Classical",
    "A71": "Benoni, Classical",
    "A72": "Benoni, Classical",
    "A73": "Benoni, Classical",
    "A74": "Benoni, Classical",
    "A75": "Benoni, Classical",
    "A76": "Benoni, Classical",
    "A77": "Benoni, Classical",
    "A78": "Benoni, Classical",
    "A79": "Benoni, Classical",
    
    "A80": "Dutch Defense",
    "A81": "Dutch Defense",
    "A82": "Dutch, Staunton Gambit",
    "A83": "Dutch, Staunton Gambit",
    "A84": "Dutch",
    "A85": "Dutch with c4 & Nc3",
    "A86": "Dutch",
    "A87": "Dutch, Leningrad, Main line",
    "A88": "Dutch, Leningrad, Main line",
    "A89": "Dutch, Leningrad, Main line",
    
    "A90": "Dutch",
    "A91": "Dutch",
    "A92": "Dutch",
    "A93": "Dutch, Stonewall, Botvinnik Variation",
    "A94": "Dutch, Stonewall with Ba3",
    "A95": "Dutch, Stonewall with Nc3",
    "A96": "Dutch, Classical Variation",
    "A97": "Dutch, Ilyin-Genevsky",
    "A98": "Dutch, Ilyin-Genevsky",
    "A99": "Dutch, Ilyin-Genevsky",
    
    "B00": "King's Pawn Opening",
    "B01": "Scandinavian Defense",
    "B02": "Alekhine's Defense",
    "B03": "Alekhine's Defense",
    "B04": "Alekhine's Defense, Modern",
    "B05": "Alekhine's Defense, Modern",
    "B06": "Robatsch (Modern) Defense",
    "B07": "Pirc Defense",
    "B08": "Pirc, Classical",
    "B09": "Pirc, Austrian Attack",
    
    "B10": "Caro-Kann Defense",
    "B11": "Caro-Kann, Two Knights, 3...Bg4",
    "B12": "Caro-Kann Defense",
    "B13": "Caro-Kann, Exchange",
    "B14": "Caro-Kann, Panov-Botvinnik Attack",
    "B15": "Caro-Kann Defense",
    "B16": "Caro-Kann, Bronstein-Larsen",
    "B17": "Caro-Kann, Steinitz Variation",
    "B18": "Caro-Kann, Classical",
    "B19": "Caro-Kann, Classical",
    
    "B20": "Sicilian, Bowdler Attack / Variable",
    "B21": "Sicilian, 2.f4 and 2.d4",
    "B22": "Sicilian, Alapin Variation",
    "B23": "Sicilian, Closed",
    "B24": "Sicilian, Closed",
    "B25": "Sicilian, Closed",
    "B26": "Sicilian, Closed",
    "B27": "Sicilian, Hyper-Accelerated Dragon",
    "B28": "Sicilian, O'Kelly Variation",
    "B29": "Sicilian, Nimzovich-Rubinstein",
    
    "B30": "Sicilian, Nimzowitsch-Rossolimo",
    "B31": "Sicilian, Rossolimo Variation",
    "B32": "Sicilian, Kalashnikov / Labourdonnais-Loewenthal",
    "B33": "Sicilian, Sveshnikov Variation",
    "B34": "Sicilian, Accelerated Fianchetto",
    "B35": "Sicilian, Accelerated Fianchetto, Modern Variation with Bc4",
    "B36": "Sicilian, Accelerated Fianchetto",
    "B37": "Sicilian, Accelerated Fianchetto",
    "B38": "Sicilian, Accelerated Fianchetto, Maroczy Bind",
    "B39": "Sicilian, Accelerated Fianchetto, Breyer Variation",
    
    "B40": "Sicilian, Pin Variation (4.e6)",
    "B41": "Sicilian, Kan",
    "B42": "Sicilian, Kan",
    "B43": "Sicilian, Kan, 5.Nc3",
    "B44": "Sicilian, Taimanov / Pin Variation",
    "B45": "Sicilian, Taimanov",
    "B46": "Sicilian, Taimanov",
    "B47": "Sicilian, Taimanov (Bastrikov)",
    "B48": "Sicilian, Taimanov",
    "B49": "Sicilian, Taimanov",
    
    "B50": "Sicilian, Wing Gambit / 2...d6",
    "B51": "Sicilian, Canal-Sokolsky (Rossolimo) Attack",
    "B52": "Sicilian, Canal-Sokolsky (Rossolimo) Attack",
    "B53": "Sicilian, Chekhover Variation",
    "B54": "Sicilian, Open Defense (Prins)",
    "B55": "Sicilian, Prins Variation",
    "B56": "Sicilian",
    "B57": "Sicilian",
    "B58": "Sicilian",
    "B59": "Sicilian, Boleslavsky Variation",
    
    "B60": "Sicilian, Richter-Rauzer",
    "B61": "Sicilian, Richter-Rauzer",
    "B62": "Sicilian, Richter-Rauzer",
    "B63": "Sicilian, Richter-Rauzer",
    "B64": "Sicilian, Richter-Rauzer",
    "B65": "Sicilian, Richter-Rauzer",
    "B66": "Sicilian, Richter-Rauzer",
    "B67": "Sicilian, Richter-Rauzer",
    "B68": "Sicilian, Richter-Rauzer",
    "B69": "Sicilian, Richter-Rauzer",
    
    "B70": "Sicilian, Dragon",
    "B71": "Sicilian, Dragon",
    "B72": "Sicilian, Dragon",
    "B73": "Sicilian, Dragon",
    "B74": "Sicilian, Dragon",
    "B75": "Sicilian, Dragon, Yugoslav Attack",
    "B76": "Sicilian, Dragon, Yugoslav Attack",
    "B77": "Sicilian, Dragon, Yugoslav Attack",
    "B78": "Sicilian, Dragon, Yugoslav Attack, 10.O-O-O",
    "B79": "Sicilian, Dragon, Yugoslav Attack, 12.h4",
    
    "B80": "Sicilian, Scheveningen",
    "B81": "Sicilian, Scheveningen",
    "B82": "Sicilian, Scheveningen",
    "B83": "Sicilian, Scheveningen",
    "B84": "Sicilian, Scheveningen",
    "B85": "Sicilian, Scheveningen",
    "B86": "Sicilian, Sozin Attack",
    "B87": "Sicilian, Sozin with ...a6 and ...b5",
    "B88": "Sicilian, Sozin",
    "B89": "Sicilian, Sozin",
    
    "B90": "Sicilian, Najdorf",
    "B91": "Sicilian, Najdorf",
    "B92": "Sicilian, Najdorf",
    "B93": "Sicilian, Najdorf, 6.f4",
    "B94": "Sicilian, Najdorf, 6.Bg5",
    "B95": "Sicilian, Najdorf, 6...e6",
    "B96": "Sicilian, Najdorf",
    "B97": "Sicilian, Najdorf",
    "B98": "Sicilian, Najdorf",
    "B99": "Sicilian, Najdorf, 7...Be7 Main line",
    
    "C00": "French Defense",
    "C01": "French, Exchange",
    "C02": "French, Advance",
    "C03": "French, Tarrasch",
    "C04": "French, Tarrasch, Guimard Main line",
    "C05": "French, Tarrasch",
    "C06": "French, Tarrasch",
    "C07": "French, Tarrasch",
    "C08": "French, Tarrasch, Open, 4.ed ed",
    "C09": "French, Tarrasch, Open Variation, Main line",
    
    "C10": "French, Paulsen Variation",
    "C11": "French, Steinitz Variation",
    "C12": "French, MacCutcheon",
    "C13": "French",
    "C14": "French, Classical",
    "C15": "French, Winawer",
    "C16": "French, Winawer",
    "C17": "French, Winawer",
    "C18": "French, Winawer",
    "C19": "French, Winawer",
    
    "C20": "King's Pawn Game",
    "C21": "Center Game",
    "C22": "Center Game",
    "C23": "Bishop's Opening",
    "C24": "Bishop's Opening",
    "C25": "Vienna Game",
    "C26": "Vienna",
    "C27": "Vienna Game",
    "C28": "Vienna Game",
    "C29": "Vienna Gambit",
    
    "C30": "King's Gambit",
    "C31": "King's Gambit Declined, Falkbeer Counter-Gambit",
    "C32": "King's Gambit Declined, Falkbeer Counter-Gambit",
    "C33": "King's Gambit Accepted",
    "C34": "King's Gambit Accepted",
    "C35": "King's Gambit Accepted, Cunningham",
    "C36": "King's Gambit Accepted, Abbazia Defense",
    "C37": "King's Gambit Accepted",
    "C38": "King's Gambit Accepted",
    "C39": "King's Gambit Accepted",
    
    "C40": "King's Knight Opening",
    "C41": "Philidor Defense",
    "C42": "Petrov's Defense",
    "C43": "Petrov, Modern Attack",
    "C44": "King's Pawn Game",
    "C45": "Scotch Game",
    "C46": "Three Knights",
    "C47": "Four Knights",
    "C48": "Four Knights",
    "C49": "Four Knights",
    
    "C50": "Italian Game",
    "C51": "Evans Gambit",
    "C52": "Evans Gambit",
    "C53": "Giuoco Piano",
    "C54": "Giuoco Piano",
    "C55": "Two Knights Defense",
    "C56": "Two Knights",
    "C57": "Two Knights",
    "C58": "Two Knights",
    "C59": "Two Knights",
    
    "C60": "Ruy Lopez",
    "C61": "Ruy Lopez, Bird's Defense",
    "C62": "Ruy Lopez, Old Steinitz Defense",
    "C63": "Ruy Lopez, Schliemann Defense",
    "C64": "Ruy Lopez, Classical Defense",
    "C65": "Ruy Lopez, Berlin Defense",
    "C66": "Ruy Lopez, Berlin Defense",
    "C67": "Ruy Lopez, Berlin Defense",
    "C68": "Ruy Lopez, Exchange",
    "C69": "Ruy Lopez, Exchange, Gligoric Variation",
    
    "C70": "Ruy Lopez",
    "C71": "Ruy Lopez",
    "C72": "Ruy Lopez",
    "C73": "Ruy Lopez",
    "C74": "Ruy Lopez",
    "C75": "Ruy Lopez",
    "C76": "Ruy Lopez",
    "C77": "Ruy Lopez",
    "C78": "Ruy Lopez",
    "C79": "Ruy Lopez, Steinitz Defense Deferred",
    
    "C80": "Ruy Lopez, Open",
    "C81": "Ruy Lopez, Open",
    "C82": "Ruy Lopez, Open",
    "C83": "Ruy Lopez, Open",
    "C84": "Ruy Lopez, Closed",
    "C85": "Ruy Lopez, Exchange Defense Doubly Deferred (DERLD)",
    "C86": "Ruy Lopez, Worrall Attack",
    "C87": "Ruy Lopez, Closed",
    "C88": "Ruy Lopez, Closed",
    "C89": "Ruy Lopez, Marshall",
    
    "C90": "Ruy Lopez, Closed",
    "C91": "Ruy Lopez, Closed",
    "C92": "Ruy Lopez, Closed",
    "C93": "Ruy Lopez, Closed, Smyslov Defense",
    "C94": "Ruy Lopez, Closed, Breyer Defense",
    "C95": "Ruy Lopez, Closed, Breyer Defense",
    "C96": "Ruy Lopez, Closed",
    "C97": "Ruy Lopez, Chigorin",
    "C98": "Ruy Lopez, Chigorin",
    "C99": "Ruy Lopez, Chigorin",

    "D00": "Queen's Pawn Game",
    "D01": "Richter-Veresov Attack",
    "D02": "Queen's Pawn Game",
    "D03": "Torre Attack (Tartakower Variation)",
    "D04": "Queen's Pawn Game",
    "D05": "Queen's Pawn Game",
    "D06": "Queen's Gambit Declined",
    "D07": "Queen's Gambit Declined; Chigorin Defense",
    "D08": "Queen's Gambit Declined; Albin Counter-Gambit",
    "D09": "Queen's Gambit Declined; Albin Counter-Gambit",

    "D10": "Queen's Gambit Declined Slav",
    "D11": "Queen's Gambit Declined Slav",
    "D12": "Queen's Gambit Declined Slav",
    "D13": "Queen's Gambit Declined Slav, Exchange Variation",
    "D14": "Queen's Gambit Declined Slav, Exchange Variation",
    "D15": "Queen's Gambit Declined Slav",
    "D16": "Queen's Gambit Declined Slav",
    "D17": "Queen's Gambit Declined Slav",
    "D18": "Queen's Gambit Declined Slav",
    "D19": "Queen's Gambit Declined Slav",

    "D20": "Queen's Gambit Accepted",
    "D21": "Queen's Gambit Accepted",
    "D22": "Queen's Gambit Accepted",
    "D23": "Queen's Gambit Accepted",
    "D24": "Queen's Gambit Accepted",
    "D25": "Queen's Gambit Accepted",
    "D26": "Queen's Gambit Accepted",
    "D27": "Queen's Gambit Accepted",
    "D28": "Queen's Gambit Accepted",
    "D29": "Queen's Gambit Accepted",

    "D30": "Queen's Gambit Declined",
    "D31": "Queen's Gambit Declined",
    "D32": "Queen's Gambit Declined, Tarrasch",
    "D33": "Queen's Gambit Declined, Tarrasch",
    "D34": "Queen's Gambit Declined, Tarrasch",
    "D35": "Queen's Gambit Declined",
    "D36": "Queen's Gambit Declined, Exchange",
    "D37": "Queen's Gambit Declined",
    "D38": "Queen's Gambit Declined, Ragozin",
    "D39": "Queen's Gambit Declined, Ragozin, Vienna Variation",

    "D40": "Queen's Gambit Declined, Semi-Tarrasch",
    "D41": "Queen's Gambit Declined, Semi-Tarrasch",
    "D42": "Queen's Gambit Declined, Semi-Tarrasch",
    "D43": "Queen's Gambit Declined Semi-Slav",
    "D44": "Queen's Gambit Declined Semi-Slav",
    "D45": "Queen's Gambit Declined Semi-Slav",
    "D46": "Queen's Gambit Declined Semi-Slav",
    "D47": "Queen's Gambit Declined Semi-Slav",
    "D48": "Queen's Gambit Declined Semi-Slav, Meran",
    "D49": "Queen's Gambit Declined Semi-Slav, Meran",

    "D50": "Queen's Gambit Declined",
    "D51": "Queen's Gambit Declined",
    "D52": "Queen's Gambit Declined",
    "D53": "Queen's Gambit Declined",
    "D54": "Queen's Gambit Declined, Anti-Neo-Orthodox Variation",
    "D55": "Queen's Gambit Declined",
    "D56": "Queen's Gambit Declined",
    "D57": "Queen's Gambit Declined, Lasker Defense",
    "D58": "Queen's Gambit Declined, Tartakower (Makagonov-Bondarevsky) System",
    "D59": "Queen's Gambit Declined, Tartakower (Makagonov-Bondarevsky) System",

    "D60": "Queen's Gambit Declined, Orthodox Defense",
    "D61": "Queen's Gambit Declined, Orthodox Defense",
    "D62": "Queen's Gambit Declined, Orthodox Defense",
    "D63": "Queen's Gambit Declined, Orthodox Defense",
    "D64": "Queen's Gambit Declined, Orthodox Defense",
    "D65": "Queen's Gambit Declined, Orthodox Defense",
    "D66": "Queen's Gambit Declined, Orthodox Defense",
    "D67": "Queen's Gambit Declined, Orthodox Defense",
    "D68": "Queen's Gambit Declined, Orthodox Defense",
    "D69": "Queen's Gambit Declined, Orthodox Defense",

    "D70": "Neo-Gruenfeld Defense",
    "D71": "Neo-Gruenfeld",
    "D72": "Neo-Gruenfeld",
    "D73": "Neo-Gruenfeld",
    "D74": "Neo-Gruenfeld",
    "D75": "Neo-Gruenfeld",
    "D76": "Neo-Gruenfeld",
    "D77": "Neo-Gruenfeld",
    "D78": "Neo-Gruenfeld",
    "D79": "Neo-Gruenfeld",

    "D80": "Gruenfeld Defense",
    "D81": "Gruenfeld",
    "D82": "Gruenfeld",
    "D83": "Gruenfeld, Grunfeld Gambit",
    "D84": "Gruenfeld, Exchange",
    "D85": "Gruenfeld, Exchange",
    "D86": "Gruenfeld, Exchange",
    "D87": "Gruenfeld, Exchange",
    "D88": "Gruenfeld, Spassky Variation",
    "D89": "Gruenfeld, Spassky Variation",

    "D90": "Gruenfeld",
    "D91": "Gruenfeld",
    "D92": "Gruenfeld",
    "D93": "Gruenfeld",
    "D94": "Gruenfeld",
    "D95": "Gruenfeld",
    "D96": "Gruenfeld",
    "D97": "Gruenfeld",
    "D98": "Gruenfeld",
    "D99": "Gruenfeld",

    "E00": "Queen's Pawn Game",
    "E01": "Catalan, Closed",
    "E02": "Catalan, Open, 5.Qa4",
    "E03": "Catalan, Open",
    "E04": "Catalan, Open, 5.Nf3",
    "E05": "Catalan, Open, Classical line",
    "E06": "Catalan, Closed, 5.Nf3",
    "E07": "Catalan, Closed",
    "E08": "Catalan, Closed",
    "E09": "Catalan, Closed",

    "E10": "Queen's Pawn Game",
    "E11": "Bogo-Indian Defense",
    "E12": "Queen's Indian Defense",
    "E13": "Queen's Indian",
    "E14": "Queen's Indian",
    "E15": "Queen's Indian",
    "E16": "Queen's Indian",
    "E17": "Queen's Indian",
    "E18": "Queen's Indian, Old Main line",
    "E19": "Queen's Indian, Old Main line",

    "E20": "Nimzo-Indian Defense",
    "E21": "Nimzo-Indian, Three Knights",
    "E22": "Nimzo-Indian, Spielmann Variation",
    "E23": "Nimzo-Indian, Spielmann",
    "E24": "Nimzo-Indian, Saemisch",
    "E25": "Nimzo-Indian, Saemisch",
    "E26": "Nimzo-Indian, Saemisch",
    "E27": "Nimzo-Indian, Saemisch Variation",
    "E28": "Nimzo-Indian, Saemisch Variation",
    "E29": "Nimzo-Indian, Saemisch",

    "E30": "Nimzo-Indian, Leningrad",
    "E31": "Nimzo-Indian, Leningrad",
    "E32": "Nimzo-Indian, Classical",
    "E33": "Nimzo-Indian, Classical",
    "E34": "Nimzo-Indian, Classical, Noa Variation",
    "E35": "Nimzo-Indian, Classical, Noa Variation",
    "E36": "Nimzo-Indian, Classical",
    "E37": "Nimzo-Indian, Classical",
    "E38": "Nimzo-Indian, Classical, 4...c5",
    "E39": "Nimzo-Indian, Classical, Pirc Variation",

    "E40": "Nimzo-Indian, 4.e3",
    "E41": "Nimzo-Indian",
    "E42": "Nimzo-Indian, 4.e3 c5, 5.Ne2 (Rubinstein)",
    "E43": "Nimzo-Indian, Fischer Variation",
    "E44": "Nimzo-Indian, Fischer Variation",
    "E45": "Nimzo-Indian, 4.e3, Bronstein (Byrne) Variation",
    "E46": "Nimzo-Indian",
    "E47": "Nimzo-Indian, 4.e3 e6 5.Bd3",
    "E48": "Nimzo-Indian, 4.e3 e6 5.Bd3",
    "E49": "Nimzo-Indian, 4.e3 e6 5.Bd3",

    "E50": "Nimzo-Indian, 4.e3 e6 5.Nf3",
    "E51": "Nimzo-Indian, 4.e3 e6 5.Nf3",
    "E52": "Nimzo-Indian, 4.e3 e6 5.Nf3",
    "E53": "Nimzo-Indian, 4.e3 e6 5.Nf3",
    "E54": "Nimzo-Indian, Gligoric System",
    "E55": "Nimzo-Indian, Gligoric System",
    "E56": "Nimzo-Indian, 4.e3, Main line",
    "E57": "Nimzo-Indian, 4.e3, Main line",
    "E58": "Nimzo-Indian, 4.e3, Main line",
    "E59": "Nimzo-Indian, 4.e3, Main line",

    "E60": "King's Indian Defense",
    "E61": "King's Indian",
    "E62": "King's Indian, Fianchetto",
    "E63": "King's Indian, Fianchetto, Panno Variation",
    "E64": "King's Indian, Fianchetto, Yugoslav System",
    "E65": "King's Indian, Yugoslav, 7.O-O",
    "E66": "King's Indian, Fianchetto, Yugoslav Panno",
    "E67": "King's Indian, Fianchetto",
    "E68": "King's Indian, Fianchetto, Classical Variation, 8.e4",
    "E69": "King's Indian, Fianchetto, Classical Main line",

    "E70": "King's Indian",
    "E71": "King's Indian, Makagonov System (5.h3)",
    "E72": "King's Indian",
    "E73": "King's Indian",
    "E74": "King's Indian, Averbakh, 6...c5",
    "E75": "King's Indian, Averbakh, Main line",
    "E76": "King's Indian, Four Pawns Attack",
    "E77": "King's Indian, Four Pawns Attack, 6.Be2",
    "E78": "King's Indian, Four Pawns Attack, with Be2 and Nf3",
    "E79": "King's Indian, Four Pawns Attack, Main line",

    "E80": "King's Indian, Saemisch Variation",
    "E81": "King's Indian, Saemisch",
    "E82": "King's Indian, Saemisch, double Fianchetto Variation",
    "E83": "King's Indian, Saemisch",
    "E84": "King's Indian, Saemisch, Panno Main line",
    "E85": "King's Indian, Saemisch, Orthodox Variation",
    "E86": "King's Indian, Saemisch, Orthodox, 7.Nge2 c6",
    "E87": "King's Indian, Saemisch, Orthodox",
    "E88": "King's Indian, Saemisch, Orthodox, 7.d5 e6",
    "E89": "King's Indian, Saemisch, Orthodox Main line",

    "E90": "King's Indian",
    "E91": "King's Indian",
    "E92": "King's Indian",
    "E93": "King's Indian, Petrosian System",
    "E94": "King's Indian, Orthodox",
    "E95": "King's Indian, Orthodox, 7...Nbd7, 8.Re1",
    "E96": "King's Indian, Orthodox, 7...Nbd7, Main line",
    "E97": "King's Indian, Orthodox, Aronin-Taimanov Variation (Yugoslav Attack / Mar del Plata Variation)",
    "E98": "King's Indian, Orthodox, Aronin-Taimanov, 9.Ne1",
    "E99": "King's Indian, Orthodox, Aronin-Taimanov, Main"
}
